### ISSUE TITLE
Omnipay gateway doesn't get initialized in cli

### ISSUE THREAD

**Issue by paulchubatyy** [colinodell/omnipay-bundle#5]
For some reasons my gateways are perfectly initialized when running thru fpm, but when I run cli commands the gateway configuration is empty. Very strange thing.

**Comment by paulchubatyy** [comment]
Never mind, using sendData instead of send.

**Comment by colinodell** [comment]
Sorry for not responding sooner, but I'm glad you were able to figure out the issue!  Let me know if you run into any other issues.
